# Generated by Django 5.1.1 on 2024-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_trip_created_at_trip_description_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
